# Overview

The purpose of this notebook is to generate a RankNet dataset to train a scoring model

## Config

In [ ]:
import pandas as pd
import cloudpickle
import pickle
import re
import jsonlines
from tqdm import tqdm 
import tensorflow as tf

In [18]:
import requests

API_URL = "https://api-inference.huggingface.co/models/DeepESP/gpt2-spanish-medium"
headers = {"Authorization": "Bearer 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"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

output = query({
	"inputs": "La música no estaba.",
})

In [19]:
output

{'error': 'unknown error',
 'warnings': ["'GPT2Config' object has no attribute 'typical_p'",
  'Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.']}

## Model

In [65]:
activation = tf.keras.layers.LeakyReLU()

#cambiar a relu
def generate_backbone(a_input_size, layers = [64,32,16]):
    input_query = tf.keras.layers.Input(shape=[a_input_size,],dtype=tf.float32,name="a")
    dense_query = tf.keras.layers.Dense(256, activation=activation)(input_query)
    dense_query = tf.keras.layers.Dropout(0.1)(dense_query)

    for units in layers:
        dense_query = tf.keras.layers.Dense(units, activation=activation)(dense_query)
        dense_query = tf.keras.layers.Dropout(0.1)(dense_query)

    dense_query = tf.keras.layers.BatchNormalization()(dense_query)
    dense_query = tf.keras.layers.Dense(8,activation=activation)(dense_query)
    output = tf.keras.layers.Dense(1,activation="linear")(dense_query)
    model = tf.keras.models.Model(input_query,output)
    return model

def ranknet(model, a_input_size, b_input_size):
    input_a = tf.keras.layers.Input(shape=[b_input_size,],dtype=tf.float32,name="a")
    input_b = tf.keras.layers.Input(shape=[b_input_size,],dtype=tf.float32,name="b")
    
    o_positive = model(input_a)
    o_negative = model(input_b)
    o_positive_minus_negative = tf.keras.layers.Subtract()([o_positive,o_negative])
    
    output = tf.keras.layers.Activation('sigmoid')(o_positive_minus_negative)
    
    model = tf.keras.models.Model([input_a,input_b],output)
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

### Backbone (underlying ranking model)

In [67]:
model = generate_backbone(1280)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 a (InputLayer)              [(None, 1280)]            0         
                                                                 
 dense_11 (Dense)            (None, 256)               327936    
                                                                 
 dropout_9 (Dropout)         (None, 256)               0         
                                                                 
 dense_12 (Dense)            (None, 64)                16448     
                                                                 
 dropout_10 (Dropout)        (None, 64)                0         
                                                                 
 dense_13 (Dense)            (None, 32)                2080      
                                                                 
 dropout_11 (Dropout)        (None, 32)                0   

### Ranknet

In [68]:
ranknet_model = ranknet(model, 1280, 1280)
ranknet_model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 a (InputLayer)                 [(None, 1280)]       0           []                               
                                                                                                  
 b (InputLayer)                 [(None, 1280)]       0           []                               
                                                                                                  
 model_2 (Functional)           (None, 1)            347201      ['a[0][0]',                      
                                                                  'b[0][0]']                      
                                                                                                  
 subtract_1 (Subtract)          (None, 1)            0           ['model_2[0][0]',          

## Training
### Load dataset

In [69]:
feature_description = {
    'a':tf.io.FixedLenFeature(shape=[], dtype=tf.string),
    'b': tf.io.FixedLenFeature(shape=[], dtype=tf.string),
    'label': tf.io.FixedLenFeature(shape=[], dtype=tf.string),
}

    
@tf.function
def _parse_example(example_proto, with_similarity :bool = False):
    example = tf.io.parse_single_example(example_proto, feature_description)
    
    a = tf.io.parse_tensor(example['a'], tf.float32)
    b = tf.io.parse_tensor(example['b'],tf.float32)
    label = tf.io.parse_tensor(example['label'],tf.float32)
        
    return (a, b), label

In [70]:
train_dataset = tf.data.TFRecordDataset(filenames = ['cover_ranknet.tfrecords'])
train_dataset = train_dataset.map(lambda x: _parse_example(x, True))
for i in train_dataset:
    break
i

((<tf.Tensor: shape=(1280,), dtype=float32, numpy=
  array([-2.2389114e-23, -2.1989489e-22, -3.3821736e-18, ...,
          2.5871570e+00,  0.0000000e+00, -4.3819432e-28], dtype=float32)>,
  <tf.Tensor: shape=(1280,), dtype=float32, numpy=
  array([-2.2389114e-23, -2.1989489e-22, -3.3821736e-18, ...,
          2.5871570e+00,  0.0000000e+00, -4.3819432e-28], dtype=float32)>),
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [71]:
EPOCHS = 100
BATCH_SIZE = 256
BUFFER_SIZE = 15*BATCH_SIZE

ranknet_model.fit(train_dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE), epochs=EPOCHS)

Epoch 1/100
201/201 [==============================] - 4s 12ms/step - loss: 0.6166
Epoch 2/100
201/201 [==============================] - 3s 13ms/step - loss: 0.5950
Epoch 3/100
201/201 [==============================] - 2s 11ms/step - loss: 0.5903
Epoch 4/100
201/201 [==============================] - 3s 13ms/step - loss: 0.5875
Epoch 5/100
201/201 [==============================] - 3s 13ms/step - loss: 0.5883
Epoch 6/100
201/201 [==============================] - 2s 12ms/step - loss: 0.5819
Epoch 7/100
201/201 [==============================] - 3s 14ms/step - loss: 0.5837
Epoch 8/100
201/201 [==============================] - 3s 13ms/step - loss: 0.5832
Epoch 9/100
201/201 [==============================] - 2s 12ms/step - loss: 0.5825
Epoch 10/100
201/201 [==============================] - 3s 13ms/step - loss: 0.5818
Epoch 11/100
201/201 [==============================] - 3s 12ms/step - loss: 0.5801
Epoch 12/100
201/201 [==============================] - 2s 12ms/step - loss: 0.5814
E

In [72]:
model.save('./cover_ranker')

2022-02-22 11:04:26.124561: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


INFO:tensorflow:Assets written to: ./cover_ranker/assets


INFO:tensorflow:Assets written to: ./cover_ranker/assets
